# This is a basic workflow to help you get started with Action

name: "Newman Tests"
on: [push, pull_request]

jobs:
  build: 
    run-on: ubuntu-latest
    container:
      image: postman/newman
    step:
      - name: Checkout
        user: actions/checkout@v2

      - name: Run API Tests
        user: newman run Restful Booker BVT.postman_collection.json -e Production.postman_environment.json
